train_config:
  epochs: 150
  batch_size: 32
  lr: 0.00001
  weight_decay: 0.6
  early_stopper:
    epochs: 10
    slope: -0.0001
  StepLR:
    gamma: 0.7
    step_size: 1
  model:
    NNClassifier: []
    ClassicAE:
      encoder: []
      decoder: []